apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: python:3.9-slim
        command: ["python", "/app/kafka_producer.py"]
        volumeMounts:
        - name: python-code
          mountPath: /app
      volumes:
      - name: python-code
        configMap:
          name: python-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: consumer
        image: python:3.9-slim
        command: ["python", "/app/kafka_consumer.py"]
        volumeMounts:
        - name: python-code
          mountPath: /app
      volumes:
      - name: python-code
        configMap:
          name: python-code