FROM python:3.9-slim

WORKDIR /app

COPY requirements-dashboard.txt .
RUN pip install -r requirements.txt

COPY src/ ./src/
COPY src/config.py .

EXPOSE 8501

CMD ["streamlit", "run", "src/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]