FROM python:3.11

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools

COPY requirements.txt .
RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

COPY src/ /app/src/
COPY src/config.py .

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

CMD ["python", "src/kafka_consumer.py"]