FROM python:3.9-slim

WORKDIR /app

# Install Java for Spark
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

COPY requirements-spark.txt .
RUN pip install -r requirements.txt

COPY src/ ./src/
COPY src/config.py .

CMD ["python", "src/spark_processor.py"]